version: '3'
services:
    web_thunder:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 8000
        environment:
            - PORT=8000
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        depends_on:
            - web_thunder
